apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig

metadata:
  name: cloud-native-platform-dev-alerts

spec:
  route:
    receiver: gmail
    groupBy:
      - alertname
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 4h

    matchers:
      - name: severity
        value: warning
        matchType: "="

  receivers:
    - name: gmail
      emailConfigs:
        - to: mashhoodhamid201@gmail.com
          from: mashhoodhamid201@gmail.com
          smarthost: smtp.gmail.com:587
          authUsername: mashhoodhamid201@gmail.com

          authPassword:
            name: alertmanager-gmail
            key: app-password

          requireTLS: true
          sendResolved: true