apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloud-native-platform-dev

resources:
  - ../../base
  - namespace.yaml

images:
  - name: docker.io/mashhood101/cloud-native-delivery-platform
    digest: sha256:33f5a03e3e085e5d28bca521c2c2bb55d61c3c0595a28723d7ad0ad412fc4c1f
