apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloud-native-platform-dev

resources:
  - ../../base
  - namespace.yaml
  - prometheus-rule.yaml
  - alertmanager-config.yaml

images:
  - name: docker.io/mashhood101/cloud-native-delivery-platform
    digest: sha256:d47cf145a19f182eaa7fefdc0125df2402567b4a7f9fae51d0c59770ce7ce561
