apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloud-native-platform-dev

resources:
  - ../../base
  - namespace.yaml

images:
  - name: docker.io/mashhood101/cloud-native-delivery-platform
    digest: sha256:c9f3db4a8fab5b74962d152fc2978331e1f6116d4a9e5c6607c7a20d7e061cdf