apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloud-native-platform-traefik-acme
  namespace: traefik
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
