apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: cloud-native-platform-dev
  namespace: argocd

spec:
  project: cloud-native-platform

  source:
    repoURL: https://github.com/managed-platform/cloud-native-delivery-platform.git
    targetRevision: main
    path: deploy/overlays/dev

  destination:
    server: https://kubernetes.default.svc
    namespace: cloud-native-platform-dev

  syncPolicy:
    automated:
      enabled: true
      prune: false
      selfHeal: false