apiVersion: v1
kind: Secret

metadata:
  name: managed-platform-github-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds

type: Opaque

stringData:
  url: https://github.com/managed-platform
  type: git
  githubAppID: "<GITHUB_APP_ID>"
  githubAppInstallationID: "<GITHUB_APP_INSTALLATION_ID>"
  githubAppPrivateKey: |
    <GITHUB_APP_PRIVATE_KEY>
